In [1]:
import torch

In [39]:
x = torch.randint(1,10, size=(3,2,2))

In [40]:
x

tensor([[[7, 9],
         [3, 3]],

        [[2, 5],
         [4, 7]],

        [[1, 2],
         [2, 1]]])

In [47]:
x.size()

torch.Size([3, 2, 2])

In [49]:
x.shape[-1]

2

In [41]:
x = x.to(torch.float)

In [42]:
x

tensor([[[7., 9.],
         [3., 3.]],

        [[2., 5.],
         [4., 7.]],

        [[1., 2.],
         [2., 1.]]])

In [43]:
x.mean(dim=0)

tensor([[3.3333, 5.3333],
        [3.0000, 3.6667]])

In [44]:
x.mean(dim=1)

tensor([[5.0000, 6.0000],
        [3.0000, 6.0000],
        [1.5000, 1.5000]])

In [45]:
x.mean(dim=2)

tensor([[8.0000, 3.0000],
        [3.5000, 5.5000],
        [1.5000, 1.5000]])

In [50]:
x

tensor([[[7., 9.],
         [3., 3.]],

        [[2., 5.],
         [4., 7.]],

        [[1., 2.],
         [2., 1.]]])

In [54]:
x.repeat(1, 2, 2)

tensor([[[7., 9., 7., 9.],
         [3., 3., 3., 3.],
         [7., 9., 7., 9.],
         [3., 3., 3., 3.]],

        [[2., 5., 2., 5.],
         [4., 7., 4., 7.],
         [2., 5., 2., 5.],
         [4., 7., 4., 7.]],

        [[1., 2., 1., 2.],
         [2., 1., 2., 1.],
         [1., 2., 1., 2.],
         [2., 1., 2., 1.]]])

In [57]:
a=torch.randn(size=(128, 1536, 1))

In [62]:
print(a)

tensor([[[-1.2382],
         [-0.8453],
         [ 1.5951],
         ...,
         [ 0.8996],
         [-0.6091],
         [-1.3157]],

        [[ 1.8629],
         [ 0.2420],
         [-1.7652],
         ...,
         [-0.5787],
         [ 0.5903],
         [-1.4418]],

        [[ 0.0467],
         [ 0.4636],
         [-0.1219],
         ...,
         [-0.0383],
         [-0.0845],
         [ 1.2769]],

        ...,

        [[-1.1970],
         [ 1.0662],
         [-0.5732],
         ...,
         [ 0.6709],
         [ 1.3805],
         [ 0.1732]],

        [[-0.4507],
         [ 0.3668],
         [ 1.2422],
         ...,
         [ 0.7098],
         [ 0.3054],
         [-1.9290]],

        [[ 0.6613],
         [ 0.7667],
         [ 1.0245],
         ...,
         [ 0.0166],
         [-0.9222],
         [-0.0791]]])


In [63]:
print(a.var(dim=2, keepdim=True))

tensor([[[nan],
         [nan],
         [nan],
         ...,
         [nan],
         [nan],
         [nan]],

        [[nan],
         [nan],
         [nan],
         ...,
         [nan],
         [nan],
         [nan]],

        [[nan],
         [nan],
         [nan],
         ...,
         [nan],
         [nan],
         [nan]],

        ...,

        [[nan],
         [nan],
         [nan],
         ...,
         [nan],
         [nan],
         [nan]],

        [[nan],
         [nan],
         [nan],
         ...,
         [nan],
         [nan],
         [nan]],

        [[nan],
         [nan],
         [nan],
         ...,
         [nan],
         [nan],
         [nan]]])


In [59]:
print(a.var(dim=2))

tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]])


In [60]:
print(a.var(dim=2, keepdim=True))

tensor([[[nan],
         [nan],
         [nan],
         ...,
         [nan],
         [nan],
         [nan]],

        [[nan],
         [nan],
         [nan],
         ...,
         [nan],
         [nan],
         [nan]],

        [[nan],
         [nan],
         [nan],
         ...,
         [nan],
         [nan],
         [nan]],

        ...,

        [[nan],
         [nan],
         [nan],
         ...,
         [nan],
         [nan],
         [nan]],

        [[nan],
         [nan],
         [nan],
         ...,
         [nan],
         [nan],
         [nan]],

        [[nan],
         [nan],
         [nan],
         ...,
         [nan],
         [nan],
         [nan]]])


In [64]:
torch.var(torch.tensor([1.23]))

tensor(nan)

In [65]:
print(a.var(dim=1, keepdim=True))

tensor([[[0.9789]],

        [[1.0127]],

        [[0.9717]],

        [[1.0353]],

        [[1.0555]],

        [[0.9718]],

        [[1.0382]],

        [[0.9526]],

        [[1.0082]],

        [[1.0482]],

        [[1.0244]],

        [[1.0402]],

        [[1.0356]],

        [[0.9246]],

        [[0.9685]],

        [[0.9839]],

        [[0.9991]],

        [[1.0071]],

        [[1.0136]],

        [[1.0282]],

        [[1.0473]],

        [[1.0193]],

        [[1.0191]],

        [[1.0399]],

        [[0.9900]],

        [[1.0201]],

        [[1.0095]],

        [[0.9925]],

        [[0.9732]],

        [[0.9650]],

        [[1.0085]],

        [[1.0009]],

        [[1.0239]],

        [[0.9823]],

        [[0.9809]],

        [[0.9881]],

        [[0.9357]],

        [[0.9458]],

        [[1.0036]],

        [[1.0383]],

        [[1.0402]],

        [[1.0114]],

        [[0.9910]],

        [[0.9863]],

        [[0.9790]],

        [[0.9925]],

        [[0.9407]],

        [[0.9

In [1]:
import pandas as pd

# Create a sample DataFrame
data = {'A': [1, 2, 3, 4, 5],
        'B': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

In [2]:
df

A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [3]:
df[3:500]

A   B
3  4  40
4  5  50